### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by AshleyWright** [Pangoraw/git-hide#2]
[Enter steps to reproduce below:]
1. Hide tree-view either by command palette or keyboard shortcut.
2. Execute 'git-hide:toggle-ignored-file-state' from command palette or keyboard shortcut.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [git-hide](https://github.com/Pangoraw/git-hide) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Users/ashleywright/.atom/packages/git-hide/lib/git-hide.coffee:14

TypeError: Cannot read property 'classList' of null
  at HideItems.hideIgnoredItems (/Users/ashleywright/.atom/packages/git-hide/lib/git-hide.coffee:14:25)
  at HideItems.hideIgnoredItems (/Users/ashleywright/.atom/packages/git-hide/lib/git-hide.coffee:1:1)
  at HideItems.toggleIgnoredItems (/Users/ashleywright/.atom/packages/git-hide/lib/git-hide.coffee:21:8)
  at atom-workspace.<anonymous> (/Users/ashleywright/.atom/packages/git-hide/lib/git-hide.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -1:09.2.0 settings-view:open (atom-text-editor.editor.is-focused)
 10x -0:58.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:48 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-one-dark-ui)
     -0:45 core:paste (atom-text-editor.editor.is-focused)
  2x -0:40.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:24.9.0 git-hide:toggle-ignored-file-state (atom-text-editor.editor.is-focused)
     -0:16.2.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  2x -0:14.1.0 php-class-tree:toggle (atom-text-editor.editor.is-focused)
     -0:09.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:08.9.0 bottom-dock:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel.ignore-hidden)
     -0:07.1.0 git-hide:toggle-ignored-file-state (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel.ignore-hidden)
     -0:04.3.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.9.0 git-hide:toggle-ignored-file-state (atom-text-editor.editor.is-focused)
     -0:03.4.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:02.2.0 git-hide:toggle-ignored-file-state (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ],
    "disabledPackages": [
      "wrap-guide",
      "background-tips"
    ]
  },
  "git-hide": {}
}
```
### Installed Packages

``` coffee
# User
Rdio, v0.6.0
aligner-php, v1.0.0
aligner-scss, v1.0.2
bottom-dock, v0.3.3
cobalt2-syntax, v0.2.0
color-picker, v2.0.11
dash, v1.3.1
editorconfig, v1.2.0
file-icons, v1.6.9
git-hide, v0.1.1
git-log, v0.4.1
grunt-manager, v0.1.6
gulp-manager, v0.2.7
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.6.1
language-SCSS, v0.4.0
language-dots, v0.0.4
linter, v1.5.1
linter-jshint, v1.2.0
linter-manager, v0.2.2
linter-php, v1.0.3
linter-scss-lint, v2.0.0
linter-xmllint, v0.0.7
markdown-preview-opener, v0.1.1
minimap, v4.13.3
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.2
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.6
minimap-selection, v4.3.0
multi-wrap-guide, v0.22.3
php-class-tree, v1.0.0
pigments, v0.14.0
project-manager, v2.5.1
quick-docs, v0.1.0
simple-drag-drop-text, v0.3.0
status-bar-clock, v2.0.1
tag, v0.3.0
todo-manager, v0.2.2

# Dev
No dev packages
```

**Comment by Pangoraw** [comment]
Thanks for reporting this bug ! I got it fixed in the new 0.1.2 version.
